version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: microservices_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  products-service:
    build: ./packages/products-service
    command: yarn start
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/microservices_db?schema=products
      JWT_SECRET: your_secret_key
    ports:
      - '3001:3001'

  orders-service:
    build: ./packages/orders-service
    command: yarn start
    depends_on:
      - db
      - products-service
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/microservices_db?schema=orders
      JWT_SECRET: your_secret_key
    ports:
      - '3002:3002'

  api-gateway:
    build: ./packages/api-gateway
    command: yarn start
    depends_on:
      - db
      - products-service
      - orders-service
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/microservices_db?schema=gateway
      JWT_SECRET: your_secret_key
    ports:
      - '3000:3000'

  frontend:
    build: ./packages/frontend
    ports:
      - '4000:3000'
    depends_on:
      - api-gateway

volumes:
  postgres_data: